services:
  - type: web
    name: quran-video-maker
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: PEXELS_API_KEY
        sync: false
      - key: PIXABAY_API_KEY
        sync: false
